In [134]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("data_indigo.csv")

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period
0,2025-08-01,IndiGo,DEL,BOM,21,0,21,3989.0,86.7,0.0,DEL-BOM,True,normal
1,2025-08-01,IndiGo,DEL,BLR,20,2,18,3777.0,88.3,0.1,DEL-BLR,True,normal
2,2025-08-01,IndiGo,BOM,BLR,14,0,14,2478.0,89.9,0.0,BOM-BLR,True,normal
3,2025-08-01,IndiGo,DEL,CCU,13,0,13,5519.0,83.6,0.0,DEL-CCU,True,normal
4,2025-08-01,IndiGo,BOM,HYD,14,0,14,4300.0,81.4,0.0,BOM-HYD,True,normal

In [5]:
df.tail()

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period
11935,2026-02-15,Air India Express,DEL,MAA,17,0,17,5759.0,85.7,0.000,DEL-MAA,False,normal
11936,2026-02-15,Air India Express,BOM,PNQ,14,1,13,5690.0,83.3,0.071,BOM-PNQ,False,normal
11937,2026-02-15,Air India Express,DEL,GOI,17,1,16,4717.0,67.5,0.059,DEL-GOI,False,normal
11938,2026-02-15,Air India Express,BLR,CCU,16,0,16,3448.0,76.9,0.000,BLR-CCU,False,normal
11939,2026-02-15,Air India Express,BOM,AMD,22,0,22,4058.0,73.7,0.000,BOM-AMD,False,normal

In [6]:
df.describe()

,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate
count,11940.000000,11940.000000,11940.000000,11940.000000,11940.000000,11940.000000
mean,18.002764,0.260050,17.742714,4313.853685,84.148568,0.014380
std,3.746813,0.692144,3.749994,1070.291595,7.391067,0.038292
min,6.000000,0.000000,5.000000,1800.000000,35.700000,0.000000
25%,15.000000,0.000000,15.000000,3634.000000,80.400000,0.000000
50%,18.000000,0.000000,18.000000,4256.000000,84.700000,0.000000
75%,20.000000,0.000000,20.000000,4900.000000,88.800000,0.000000
max,35.000000,12.000000,35.000000,12436.000000,99.000000,0.615000

In [7]:
df.loc[0]

date                 2025-08-01
airline                  IndiGo
source                      DEL
destination                 BOM
scheduled_flights            21
cancelled_flights             0
flown_flights                21
avg_fare_inr             3989.0
on_time_pct                86.7
cancellation_rate           0.0
route                   DEL-BOM
is_indigo                  True
period                   normal
Name: 0, dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11940 entries, 0 to 11939
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               11940 non-null  object
 1   airline            11940 non-null  object
 2   source             11940 non-null  object
 3   destination        11940 non-null  object
 4   scheduled_flights  11940 non-null  int64
 5   cancelled_flights  11940 non-null  int64
 6   flown_flights      11940 non-null  int64
 7   avg_fare_inr       11940 non-null  float64
 8   on_time_pct        11940 non-null  float64
 9   cancellation_rate  11940 non-null  float64
 10  route              11940 non-null  object
 11  is_indigo          11940 non-null  bool
 12  period             11940 non-null  object
dtypes: bool(1), float64(3), int64(3), object(6)
memory usage: 1.1+ MB

In [13]:
df.shape

(11940, 13)

In [14]:
df["airline"]

0                   IndiGo
1                   IndiGo
2                   IndiGo
3                   IndiGo
4                   IndiGo
               ...
11935    Air India Express
11936    Air India Express
11937    Air India Express
11938    Air India Express
11939    Air India Express
Name: airline, Length: 11940, dtype: object

In [15]:
df[["flown_flights", "airline"]]

       flown_flights            airline
0                 21             IndiGo
1                 18             IndiGo
2                 14             IndiGo
3                 13             IndiGo
4                 14             IndiGo
...              ...                ...
11935             17  Air India Express
11936             13  Air India Express
11937             16  Air India Express
11938             16  Air India Express
11939             22  Air India Express

[11940 rows x 2 columns]

In [17]:
df.loc[0:20, ["flown_flights", "airline"]]

    flown_flights    airline
0              21     IndiGo
1              18     IndiGo
2              14     IndiGo
3              13     IndiGo
4              14     IndiGo
5              12     IndiGo
6              15     IndiGo
7              24     IndiGo
8              17     IndiGo
9              20     IndiGo
10             19     IndiGo
11             11     IndiGo
12             23  Air India
13             18  Air India
14             16  Air India
15             11  Air India
16             21  Air India
17             12  Air India
18             16  Air India
19             19  Air India
20             15  Air India

In [18]:
df.iloc[0:20, 3:12]

,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo
0,BOM,21,0,21,3989.0,86.7,0.000,DEL-BOM,True
1,BLR,20,2,18,3777.0,88.3,0.100,DEL-BLR,True
2,BLR,14,0,14,2478.0,89.9,0.000,BOM-BLR,True
3,CCU,13,0,13,5519.0,83.6,0.000,DEL-CCU,True
4,HYD,14,0,14,4300.0,81.4,0.000,BOM-HYD,True
5,HYD,12,0,12,4188.0,78.7,0.000,DEL-HYD,True
6,MAA,15,0,15,2436.0,86.3,0.000,BLR-MAA,True
7,MAA,24,0,24,4096.0,83.2,0.000,DEL-MAA,True
8,PNQ,17,0,17,5151.0,78.2,0.000,BOM-PNQ,True
9,GOI,22,2,20,3591.0,88.7,0.091,DEL-GOI,True
10,CCU,20,1,19,3922.0,76.0,0.050,BLR-CCU,True
11,AMD,11,0,11,4931.0,93.1,0.000,BOM-AMD,True
12,BOM,23,0,23,3619.0,94.0,0.000,DEL-BOM,False
13,BLR,18,0,18,4278.0,83.2,0.000,DEL-BLR,False
14,BLR,16,0,16,4521.0,80.3,0.000,BOM-BLR,False
15,CCU,11,0,11,5024.0,87.0,0.000,DEL-CCU,False
16,HYD,22,1,21,5072.0,83.1,0.045,BOM-HYD,False
17,HYD,12,0,12,4467.0,86.6,0.000,DEL-HYD,False
18,MAA,17,1,16,3478.0,86.3,0.059,BLR-MAA,False
19,MAA,20,1,19,2473.0,84.8,0.050,DEL-MAA,False

In [19]:
df.isnull()

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11935,False,False,False,False,False,False,False,False,False,False,False,False,False
11936,False,False,False,False,False,False,False,False,False,False,False,False,False
11937,False,False,False,False,False,False,False,False,False,False,False,False,False
11938,False,False,False,False,False,False,False,False,False,False,False,False,False
11939,False,False,False,False,False,False,False,False,False,False,False,False,False

In [20]:
df.dropna()

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period
0,2025-08-01,IndiGo,DEL,BOM,21,0,21,3989.0,86.7,0.000,DEL-BOM,True,normal
1,2025-08-01,IndiGo,DEL,BLR,20,2,18,3777.0,88.3,0.100,DEL-BLR,True,normal
2,2025-08-01,IndiGo,BOM,BLR,14,0,14,2478.0,89.9,0.000,BOM-BLR,True,normal
3,2025-08-01,IndiGo,DEL,CCU,13,0,13,5519.0,83.6,0.000,DEL-CCU,True,normal
4,2025-08-01,IndiGo,BOM,HYD,14,0,14,4300.0,81.4,0.000,BOM-HYD,True,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11935,2026-02-15,Air India Express,DEL,MAA,17,0,17,5759.0,85.7,0.000,DEL-MAA,False,normal
11936,2026-02-15,Air India Express,BOM,PNQ,14,1,13,5690.0,83.3,0.071,BOM-PNQ,False,normal
11937,2026-02-15,Air India Express,DEL,GOI,17,1,16,4717.0,67.5,0.059,DEL-GOI,False,normal
11938,2026-02-15,Air India Express,BLR,CCU,16,0,16,3448.0,76.9,0.000,BLR-CCU,False,normal
11939,2026-02-15,Air India Express,BOM,AMD,22,0,22,4058.0,73.7,0.000,BOM-AMD,False,normal

In [30]:
df["date"] = pd.to_datetime(df["date"])
df.dtypes

date                 datetime64[ns]
airline                      object
source                       object
destination                  object
scheduled_flights             int64
cancelled_flights             int64
flown_flights                 int64
avg_fare_inr                float64
on_time_pct                 float64
cancellation_rate           float64
route                        object
is_indigo                      bool
period                       object
dtype: object

In [31]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

In [32]:
dec_2025 = df[(df["year"] == 2025) & (df["month"] == 12)]

In [33]:
dec_2025.shape

(1860, 16)

In [35]:
dec_2025

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period,year,month,day
7320,2025-12-01,IndiGo,DEL,BOM,14,0,14,3563.0,79.6,0.000,DEL-BOM,True,normal,2025,12,1
7321,2025-12-01,IndiGo,DEL,BLR,23,0,23,2212.0,99.0,0.000,DEL-BLR,True,normal,2025,12,1
7322,2025-12-01,IndiGo,BOM,BLR,21,1,20,4070.0,80.0,0.048,BOM-BLR,True,normal,2025,12,1
7323,2025-12-01,IndiGo,DEL,CCU,14,0,14,5368.0,91.4,0.000,DEL-CCU,True,normal,2025,12,1
7324,2025-12-01,IndiGo,BOM,HYD,17,0,17,4958.0,84.0,0.000,BOM-HYD,True,normal,2025,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9175,2025-12-31,Air India Express,DEL,MAA,16,0,16,2830.0,88.1,0.000,DEL-MAA,False,recovery,2025,12,31
9176,2025-12-31,Air India Express,BOM,PNQ,25,0,25,3468.0,92.6,0.000,BOM-PNQ,False,recovery,2025,12,31
9177,2025-12-31,Air India Express,DEL,GOI,13,0,13,4823.0,87.3,0.000,DEL-GOI,False,recovery,2025,12,31
9178,2025-12-31,Air India Express,BLR,CCU,16,1,15,3408.0,90.6,0.062,BLR-CCU,False,recovery,2025,12,31
9179,2025-12-31,Air India Express,BOM,AMD,16,0,16,4211.0,89.0,0.000,BOM-AMD,False,recovery,2025,12,31

In [39]:
df["destination"].duplicated()

0        False
1        False
2         True
3        False
4        False
         ...
11935     True
11936     True
11937     True
11938     True
11939     True
Name: destination, Length: 11940, dtype: bool

In [38]:
flights_cancelled = dec_2025["cancelled_flights"].sum()
print("Total Flights Cancelled in Dec 2025:", flights_cancelled)

Total Flights Cancelled in Dec 2025: 1031

In [45]:
cancelled_by_airline = (
    df.groupby("airline", as_index=False)["cancelled_flights"].sum().sort_values(by="cancelled_flights", ascending=False)
)

print(cancelled_by_airline)

             airline  cancelled_flights
3             IndiGo               1350
0          Air India                448
4           SpiceJet                447
1  Air India Express                437
2          Akasa Air                423

In [90]:
df = pd.read_csv("indigo_flights.csv")

In [75]:
df

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct
0,2025-12-01,IndiGo,BOM,BLR,21,1,20,4070.0,80.0
1,2025-12-01,IndiGo,DEL,GOI,20,1,19,3864.0,84.0
2,2025-12-02,IndiGo,DEL,BOM,24,1,23,4122.0,65.1
3,2025-12-02,IndiGo,DEL,BLR,19,2,17,3508.0,57.1
4,2025-12-02,IndiGo,BOM,BLR,20,1,19,3983.0,71.0
...,...,...,...,...,...,...,...,...,...
262,2025-12-31,IndiGo,DEL,CCU,20,2,18,4301.0,70.6
263,2025-12-31,IndiGo,DEL,HYD,21,1,20,1800.0,64.6
264,2025-12-31,IndiGo,BOM,PNQ,20,1,19,4518.0,60.5
265,2025-12-31,IndiGo,DEL,GOI,18,1,17,6338.0,61.2
266,2025-12-31,IndiGo,BOM,AMD,20,2,18,1800.0,79.1

In [92]:
Indigo_route = (
    df.groupby(["source", "destination"], as_index=False).agg(total_cancelled=("cancelled_flights", "sum"), scheduled_flights=("scheduled_flights", "sum"), average_fare=("avg_fare_inr", "mean")))
Indigo_route

   source destination  total_cancelled  scheduled_flights  average_fare
0     BLR         CCU               61                421   4002.500000
1     BLR         MAA               71                385   4456.571429
2     BOM         AMD               60                387   4560.545455
3     BOM         BLR               66                465   4374.000000
4     BOM         HYD               56                405   4102.590909
5     BOM         PNQ               70                430   4149.260870
6     DEL         BLR               59                459   4590.913043
7     DEL         BOM               81                466   4337.720000
8     DEL         CCU               51                313   4258.315789
9     DEL         GOI               61                373   4514.095238
10    DEL         HYD               70                392   3870.590909
11    DEL         MAA               58                395   4551.950000

In [80]:
print(df.shape)

(267, 9)

In [107]:
df["date"] = pd.to_datetime(df["date"])
df = df[(df["airline"] == "IndiGo") & 
    (df["date"].dt.year ==2025) & 
    (df["date"].dt.month == 12) & 
    (df["cancelled_flights"] > 0)]
df.reset_index(drop=True, inplace=True)

In [108]:
df

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period,crisis_severity
0,2025-12-01,IndiGo,BOM,BLR,21,1,20,4070.0,80.0,0.048,BOM-BLR,True,normal,Low
1,2025-12-01,IndiGo,DEL,GOI,20,1,19,3864.0,84.0,0.050,DEL-GOI,True,normal,Low
2,2025-12-02,IndiGo,DEL,BOM,24,1,23,4122.0,65.1,0.042,DEL-BOM,True,crisis,Low
3,2025-12-02,IndiGo,DEL,BLR,19,2,17,3508.0,57.1,0.105,DEL-BLR,True,crisis,Moderate
4,2025-12-02,IndiGo,BOM,BLR,20,1,19,3983.0,71.0,0.050,BOM-BLR,True,crisis,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,2025-12-31,IndiGo,DEL,CCU,20,2,18,4301.0,70.6,0.100,DEL-CCU,True,recovery,Moderate
263,2025-12-31,IndiGo,DEL,HYD,21,1,20,1800.0,64.6,0.048,DEL-HYD,True,recovery,Low
264,2025-12-31,IndiGo,BOM,PNQ,20,1,19,4518.0,60.5,0.050,BOM-PNQ,True,recovery,Low
265,2025-12-31,IndiGo,DEL,GOI,18,1,17,6338.0,61.2,0.056,DEL-GOI,True,recovery,Low
266,2025-12-31,IndiGo,BOM,AMD,20,2,18,1800.0,79.1,0.100,BOM-AMD,True,recovery,Moderate

In [109]:
original_df = df.copy()

In [114]:
conditions = [df["cancelled_flights"] >= 3,
        df["cancelled_flights"] >= 2,
        df["cancelled_flights"] == 1,
    ]

choices = ["High", "Moderate", "Low"]

df["crisis_severity"] = np.select(
    conditions,
    choices,
    default="Low"
)

df[["cancelled_flights", "crisis_severity"]].head()

   cancelled_flights crisis_severity
0                  1             Low
1                  1             Low
2                  1             Low
3                  2        Moderate
4                  1             Low

In [117]:
df

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,on_time_pct,cancellation_rate,route,is_indigo,period,crisis_severity
0,2025-12-01,IndiGo,BOM,BLR,21,1,20,4070.0,80.0,0.048,BOM-BLR,True,normal,Low
1,2025-12-01,IndiGo,DEL,GOI,20,1,19,3864.0,84.0,0.050,DEL-GOI,True,normal,Low
2,2025-12-02,IndiGo,DEL,BOM,24,1,23,4122.0,65.1,0.042,DEL-BOM,True,crisis,Low
3,2025-12-02,IndiGo,DEL,BLR,19,2,17,3508.0,57.1,0.105,DEL-BLR,True,crisis,Moderate
4,2025-12-02,IndiGo,BOM,BLR,20,1,19,3983.0,71.0,0.050,BOM-BLR,True,crisis,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,2025-12-31,IndiGo,DEL,CCU,20,2,18,4301.0,70.6,0.100,DEL-CCU,True,recovery,Moderate
263,2025-12-31,IndiGo,DEL,HYD,21,1,20,1800.0,64.6,0.048,DEL-HYD,True,recovery,Low
264,2025-12-31,IndiGo,BOM,PNQ,20,1,19,4518.0,60.5,0.050,BOM-PNQ,True,recovery,Low
265,2025-12-31,IndiGo,DEL,GOI,18,1,17,6338.0,61.2,0.056,DEL-GOI,True,recovery,Low
266,2025-12-31,IndiGo,BOM,AMD,20,2,18,1800.0,79.1,0.100,BOM-AMD,True,recovery,Moderate

In [132]:
df["fare"] = np.select(
    [
        df["avg_fare_inr"] >= 7000,
        df["avg_fare_inr"] >= 3000,
    ],
    [
        "High",
        "Medium"
    ],
    default="Low"
)

In [133]:
df

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,cancellation_rate,route,period,crisis_severity,fare
0,2025-12-01,IndiGo,BOM,BLR,21,1,20,4070.0,0.048,BOM-BLR,normal,Low,Medium
1,2025-12-01,IndiGo,DEL,GOI,20,1,19,3864.0,0.050,DEL-GOI,normal,Low,Medium
2,2025-12-02,IndiGo,DEL,BOM,24,1,23,4122.0,0.042,DEL-BOM,crisis,Low,Medium
3,2025-12-02,IndiGo,DEL,BLR,19,2,17,3508.0,0.105,DEL-BLR,crisis,Moderate,Medium
4,2025-12-02,IndiGo,BOM,BLR,20,1,19,3983.0,0.050,BOM-BLR,crisis,Low,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,2025-12-31,IndiGo,DEL,CCU,20,2,18,4301.0,0.100,DEL-CCU,recovery,Moderate,Medium
263,2025-12-31,IndiGo,DEL,HYD,21,1,20,1800.0,0.048,DEL-HYD,recovery,Low,Low
264,2025-12-31,IndiGo,BOM,PNQ,20,1,19,4518.0,0.050,BOM-PNQ,recovery,Low,Medium
265,2025-12-31,IndiGo,DEL,GOI,18,1,17,6338.0,0.056,DEL-GOI,recovery,Low,Medium
266,2025-12-31,IndiGo,BOM,AMD,20,2,18,1800.0,0.100,BOM-AMD,recovery,Moderate,Low

In [123]:
df = df.drop("on_time_pct", axis=1)

In [124]:
df = df.drop("is_indigo", axis=1)

In [129]:
cleaned_data = df
cleaned_data

,date,airline,source,destination,scheduled_flights,cancelled_flights,flown_flights,avg_fare_inr,cancellation_rate,route,period,crisis_severity,fare
0,2025-12-01,IndiGo,BOM,BLR,21,1,20,4070.0,0.048,BOM-BLR,normal,Low,Medium
1,2025-12-01,IndiGo,DEL,GOI,20,1,19,3864.0,0.050,DEL-GOI,normal,Low,Medium
2,2025-12-02,IndiGo,DEL,BOM,24,1,23,4122.0,0.042,DEL-BOM,crisis,Low,Medium
3,2025-12-02,IndiGo,DEL,BLR,19,2,17,3508.0,0.105,DEL-BLR,crisis,Moderate,Medium
4,2025-12-02,IndiGo,BOM,BLR,20,1,19,3983.0,0.050,BOM-BLR,crisis,Low,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,2025-12-31,IndiGo,DEL,CCU,20,2,18,4301.0,0.100,DEL-CCU,recovery,Moderate,Medium
263,2025-12-31,IndiGo,DEL,HYD,21,1,20,1800.0,0.048,DEL-HYD,recovery,Low,Low fare
264,2025-12-31,IndiGo,BOM,PNQ,20,1,19,4518.0,0.050,BOM-PNQ,recovery,Low,Medium
265,2025-12-31,IndiGo,DEL,GOI,18,1,17,6338.0,0.056,DEL-GOI,recovery,Low,Medium
266,2025-12-31,IndiGo,BOM,AMD,20,2,18,1800.0,0.100,BOM-AMD,recovery,Moderate,Low fare

In [130]:
cleaned_data.to_csv("IndiGo_Cleaned_Data.csv", index=False)